name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 2d0d83573e8a343babd70b1d30f26c52ce855b51942e4e854aa2021c85cdd7ab07-d5683945-fe74-4531-b6b4-68737e0656e900f26300e5c2210f-7027e13b-8560-4e95-9471-747394a9ec8c00f26300e5c2210f
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          skip_app_build: true
